BakConfig:
  Database:
    - host: "yunxue521.top"
      port: "32306"
      user: root
      password: "1qaz@WSX"
      DBName: ctblog
      isAllDBBak: true
      BackupCycle:  "*/1 * * * * ?"
      KeepNumber: 7
      DingConf:
        isDingSend: false
        webhook: https://oapi.dingtalk.com/robot/send?access_token=f7af721d634b0fafe6a01826d795aadf0454250430ea169ec32f9a507cab881a
      OssConf:
        isOssSave: false
        type: ali
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accesskey: "LTAI5t61CemFMNzTivCmj167"
        secretkey: "xIJK3KTplZj9d7OLa417eAyedsWBCK"
        bucketName: "mysqldata12138"
        directory: "mysql/"
    - host: "yunxue521.top"
      port: "32306"
      password: "1qaz@WSX"
      DBName: ctblogdddd
      isAllDBBak: false
      BackupCycle:  "*/10 * * * * ?"
      KeepNumber: 7
      DingConf:
        isDingSend: true
        webhook: https://oapi.dingtalk.com/robot/send?access_token=f7af721d634b0fafe6a01826d795aadf0454250430ea169ec32f9a507cab881a
      OssConf:
        isOssSave: false
        type: ali
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accesskey: "LTAI5t61CemFMNzTivCmj167"
        secretkey: "xIJK3KTplZj9d7OLa417eAyedsWBCK"
        bucketName: "mysqldata12138"
        directory: "mysql/"